### ISSUE TITLE
I can not seem to run

### ISSUE THREAD

**Issue by TingHsi** [Trungmaster5/WebOCR#1]
webcam.min.js:1 [Deprecation] getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

---

webcam.min.js:1 The following error occured:  DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
angular.min.js:118 TypeError: Cannot read property 'getContext' of null

---

Can you help us to try it?

**Comment by Trungmaster5** [comment]
Hi there, 
How did you start your local server ? 
I recommend you to use live-server lib via npm as follow: 
$npm install -g live-server 
$live-server
